### ISSUE TITLE
Some NUnit tests not pass

### ISSUE THREAD

**Issue by kvvinokurov** [sadomovalex/camlex#93]
This tests:
- test_THAT_expression_with_double_IS_translated_sucessfully
- test_THAT_expression_with_float_IS_translated_sucessfully
- test_THAT_expression_with_decimal_IS_translated_sucessfully

http://prntscr.com/jues5h

I have a Russian localization on my computer. 1.5 it will be 1,5.
I think it's worth adjusting the test in a way that would not depend on the localization of the operating system.

**Comment by sadomovalex** [comment]
You are welcome to create pull request with fix as well)

**Comment by kvvinokurov** [comment]
I will write just what needs to be corrected. :)

Class "NumberValueOperand"
from:
        public override XElement ToCaml()
        {
            return
                new XElement(Tags.Value, new XAttribute(Attributes.Type, TypeName),
                             new XText(Value.ToString()));
        }

to:
public override XElement ToCaml()
        {
            return
                new XElement(Tags.Value, new XAttribute(Attributes.Type, TypeName),
                             new XText(Value.ToString(CultureInfo.InvariantCulture)));
        }
